// src/components/sections/PortfolioSection.vue
<template>
  <SectionContainer
    tag="Proven Results"
    title="Real Value Delivered Fast"
    subtitle="See how we've helped companies ship reliable software quickly, slashing their budgets without compromising on quality."
    bg-alt
  >
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mb-8">
      <BaseCard
        v-for="item in featuredItems"
        :key="item.id"
        :glass="true"
        class="flex flex-col h-full"
      >
        <div class="flex items-center justify-between mb-4">
          <BaseBadge variant="dark">{{ item.industry }}</BaseBadge>
          <span class="text-xs text-slate-500 dark:text-slate-400 font-semibold">{{ item.completionYear }}</span>
        </div>

        <h3 class="text-xl font-bold text-slate-900 dark:text-white mb-1.5 leading-snug">{{ item.title }}</h3>
        <p class="text-xs font-semibold text-brand-hover dark:text-brand-yellow mb-3">Client: {{ item.client }}</p>
        <p class="text-sm text-slate-600 dark:text-slate-300 leading-relaxed mb-6">{{ item.summary }}</p>

        <!-- Measurable Results Grid -->
        <div class="p-4 rounded-xl backdrop-blur-md bg-slate-50/90 dark:bg-slate-800/60 border border-slate-200/70 dark:border-white/10 mb-6 flex flex-col gap-3 shadow-xs">
          <div v-for="res in item.results" :key="res.label" class="flex flex-col">
            <span class="text-xl font-extrabold text-slate-900 dark:text-white leading-none">{{ res.metric }}</span>
            <span class="text-xs font-medium text-slate-600 dark:text-slate-300 mt-1">{{ res.label }}</span>
          </div>
        </div>

        <div class="mt-auto flex items-center justify-between gap-2 pt-2">
          <div class="flex flex-wrap gap-1">
            <span v-for="t in item.technologies.slice(0, 3)" :key="t" class="text-[11px] font-medium px-2 py-0.5 rounded backdrop-blur-sm bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-white/10">
              {{ t }}
            </span>
          </div>
          <a v-if="item.url" :href="item.url" target="_blank" rel="noopener noreferrer" class="inline-flex items-center gap-1 text-xs font-bold text-brand-hover dark:text-brand-yellow hover:underline">
            <span>Launch Live Demo 🚀</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
          </a>
          <router-link v-else :to="`/portfolio/${item.slug}`" class="inline-flex items-center gap-1 text-xs font-bold text-slate-900 dark:text-white hover:text-brand-hover dark:hover:text-brand-yellow transition-colors">
            <span>Read Case Study</span>
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
          </router-link>
        </div>
      </BaseCard>
    </div>

    <div class="text-center">
      <BaseButton to="/portfolio" variant="outline" size="md">
        View All Case Studies
      </BaseButton>
    </div>
  </SectionContainer>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import SectionContainer from '@/components/layout/SectionContainer.vue';
import BaseCard from '@/components/common/BaseCard.vue';
import BaseBadge from '@/components/common/BaseBadge.vue';
import BaseButton from '@/components/common/BaseButton.vue';
import { portfolioData } from '@/data/portfolio';

const featuredItems = computed(() => portfolioData.filter((i) => i.featured));
</script>

// components/sections/PortfolioSection.tsx
import React from 'react';
import Link from 'next/link';
import { ExternalLink, ArrowRight } from 'lucide-react';
import { portfolioData } from '@/src/data/portfolio';
import { BaseBadge } from '@/components/common/BaseBadge';

export const PortfolioSection: React.FC = () => {
  const featured = portfolioData.filter((p) => p.featured);

  return (
    <section className="py-20 relative">
      <div className="container">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <BaseBadge variant="amber" className="mb-4 uppercase tracking-widest text-[10px]">
            Selected Works
          </BaseBadge>
          <h2 className="text-3xl md:text-5xl font-extrabold text-slate-900 dark:text-white tracking-tight mb-4">
            Proven Client & Open Source Software
          </h2>
          <p className="text-slate-600 dark:text-slate-300 text-base md:text-lg">
            Explore live platforms, SaaS tools, and open source projects built by SHP Technology engineers.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {featured.map((project) => (
            <div
              key={project.id}
              className="glass-card p-8 rounded-3xl flex flex-col justify-between group hover:border-amber-500/50 transition-all duration-300"
            >
              <div>
                <div className="flex items-center justify-between gap-2 mb-4">
                  <BaseBadge variant="blue" className="text-[10px]">
                    {project.industry}
                  </BaseBadge>
                  <span className="text-xs text-slate-400 font-semibold">{project.completionYear}</span>
                </div>

                <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3 group-hover:text-amber-500 transition-colors">
                  {project.title}
                </h3>

                <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed mb-6">
                  {project.summary}
                </p>

                <div className="flex flex-wrap gap-2 mb-6">
                  {project.technologies.slice(0, 4).map((tech, idx) => (
                    <span
                      key={idx}
                      className="px-2.5 py-1 rounded-md bg-slate-100 dark:bg-slate-800 text-[11px] font-semibold text-slate-700 dark:text-slate-300"
                    >
                      {tech}
                    </span>
                  ))}
                </div>
              </div>

              <div className="flex items-center justify-between pt-4 border-t border-slate-200/60 dark:border-slate-800">
                <Link
                  href={`/portfolio/${project.slug}`}
                  className="text-xs font-bold text-amber-500 hover:text-amber-600 flex items-center gap-1.5"
                >
                  <span>Read Case Study</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>

                {project.url && (
                  <a
                    href={project.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:text-amber-500 transition-colors"
                    title="Visit Live Application"
                  >
                    <ExternalLink className="w-4 h-4" />
                  </a>
                )}
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};
