// src/components/sections/ServicesGrid.vue
<template>
  <SectionContainer
    tag="Our Services"
    title="The Software and Services We Offer"
    subtitle="We write clean, simple, and secure code to solve your business needs and make your products run smoothly."
  >
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
      <BaseCard
        v-for="service in servicesData"
        :key="service.id"
        :glass="true"
        class="flex flex-col h-full"
      >
        <!-- Service Icon -->
        <div class="w-12 h-12 rounded-xl backdrop-blur-md bg-slate-100 dark:bg-slate-800/80 border border-slate-200 dark:border-white/10 flex items-center justify-center text-brand-hover dark:text-brand-yellow mb-4 shadow-sm">
          <component :is="getIconComponent(service.icon)" class="w-6 h-6" />
        </div>

        <div class="mb-3">
          <BaseBadge variant="yellow">{{ service.category }}</BaseBadge>
        </div>

        <h3 class="text-xl font-bold text-slate-900 dark:text-white mb-2 leading-snug">{{ service.title }}</h3>
        <p class="text-sm text-slate-600 dark:text-slate-300 mb-4 leading-relaxed">{{ service.shortDescription }}</p>

        <!-- Problem Solved Callout -->
        <div class="p-3.5 rounded-xl backdrop-blur-md bg-slate-50/90 dark:bg-slate-800/60 border border-slate-200/70 dark:border-white/10 mb-4 shadow-xs">
          <span class="text-xs font-bold text-slate-900 dark:text-white block">Problem Solved:</span>
          <p class="text-xs text-slate-600 dark:text-slate-300 mt-1 leading-normal">{{ service.problemSolved }}</p>
        </div>

        <!-- Tech Badges -->
        <div class="flex flex-wrap gap-2 mb-6">
          <span v-for="tech in service.technologies.slice(0, 3)" :key="tech" class="text-xs font-medium px-2.5 py-0.5 rounded-full backdrop-blur-sm bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-white/10">
            {{ tech }}
          </span>
        </div>

        <!-- Action Link -->
        <div class="mt-auto">
          <router-link :to="`/services/${service.slug}`" class="inline-flex items-center gap-2 text-sm font-semibold text-slate-900 dark:text-white hover:text-brand-hover dark:hover:text-brand-yellow transition-colors group">
            <span>Learn More & View Deliverables</span>
            <svg class="group-hover:translate-x-1 transition-transform" xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>
          </router-link>
        </div>
      </BaseCard>
    </div>
  </SectionContainer>
</template>

<script setup lang="ts">
import SectionContainer from '@/components/layout/SectionContainer.vue';
import BaseCard from '@/components/common/BaseCard.vue';
import BaseBadge from '@/components/common/BaseBadge.vue';
import { servicesData } from '@/data/services';
import {
  Code2,
  Cloud,
  Cpu,
  Network,
  ShieldCheck,
  Layout
} from 'lucide-vue-next';

const iconMap: Record<string, any> = {
  Code2,
  Cloud,
  Cpu,
  Network,
  ShieldCheck,
  Layout
};

const getIconComponent = (iconName: string) => iconMap[iconName] || Code2;
</script>

// components/sections/ServicesGrid.tsx
import React from 'react';
import Link from 'next/link';
import { ArrowRight, Code2, Cloud, Cpu, Network, ShieldCheck, Layout } from 'lucide-react';
import { servicesData } from '@/src/data/services';
import { BaseBadge } from '@/components/common/BaseBadge';

const iconMap: Record<string, React.ReactNode> = {
  Code2: <Code2 className="w-6 h-6 text-amber-500" />,
  Cloud: <Cloud className="w-6 h-6 text-amber-500" />,
  Cpu: <Cpu className="w-6 h-6 text-amber-500" />,
  Network: <Network className="w-6 h-6 text-amber-500" />,
  ShieldCheck: <ShieldCheck className="w-6 h-6 text-amber-500" />,
  Layout: <Layout className="w-6 h-6 text-amber-500" />
};

export const ServicesGrid: React.FC = () => {
  return (
    <section className="py-20 relative">
      <div className="container">
        <div className="text-center max-w-3xl mx-auto mb-16">
          <BaseBadge variant="amber" className="mb-4 uppercase tracking-widest text-[10px]">
            Engineering Capabilities
          </BaseBadge>
          <h2 className="text-3xl md:text-5xl font-extrabold text-slate-900 dark:text-white tracking-tight mb-4">
            Bespoke Engineering Solutions
          </h2>
          <p className="text-slate-600 dark:text-slate-300 text-base md:text-lg">
            High-performance web software, cloud infrastructure, and AI automation tailored to your business goals.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {servicesData.map((service) => (
            <Link
              key={service.id}
              href={`/services/${service.slug}`}
              className="group glass-card p-8 rounded-3xl flex flex-col justify-between hover:border-amber-500/50 transition-all duration-300 relative overflow-hidden"
            >
              <div>
                <div className="p-3.5 rounded-2xl bg-amber-500/10 dark:bg-amber-500/15 w-fit mb-6 group-hover:scale-110 transition-transform duration-300">
                  {iconMap[service.icon] || <Code2 className="w-6 h-6 text-amber-500" />}
                </div>

                <BaseBadge variant="blue" className="mb-3 text-[10px]">
                  {service.category}
                </BaseBadge>

                <h3 className="text-xl font-bold text-slate-900 dark:text-white mb-3 group-hover:text-amber-500 transition-colors">
                  {service.title}
                </h3>

                <p className="text-slate-600 dark:text-slate-400 text-sm leading-relaxed mb-6">
                  {service.shortDescription}
                </p>
              </div>

              <div className="flex items-center gap-2 text-xs font-bold text-amber-500 group-hover:translate-x-1 transition-transform">
                <span>Explore Technical Specs</span>
                <ArrowRight className="w-4 h-4" />
              </div>
            </Link>
          ))}
        </div>
      </div>
    </section>
  );
};
