// src/components/common/FaqAccordion.vue
<template>
  <div class="space-y-4">
    <div
      v-for="(item, index) in items"
      :key="index"
      class="glass-card overflow-hidden transition-all duration-200 border border-slate-200/80 dark:border-white/10"
    >
      <button
        type="button"
        class="w-full px-6 py-5 flex items-center justify-between text-left font-bold text-lg text-slate-900 dark:text-white hover:text-brand-hover dark:hover:text-brand-yellow transition-colors"
        :aria-expanded="openIndex === index"
        :aria-controls="`faq-answer-${index}`"
        @click="toggle(index)"
      >
        <span>{{ item.question }}</span>
        <span class="ml-4 flex-shrink-0 w-8 h-8 rounded-full bg-slate-100 dark:bg-slate-800 flex items-center justify-center text-slate-900 dark:text-white transition-transform duration-300" :class="{ 'rotate-180 bg-brand-light dark:bg-slate-700': openIndex === index }">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg>
        </span>
      </button>

      <Transition name="accordion">
        <div v-if="openIndex === index" :id="`faq-answer-${index}`" class="px-6 pb-6 text-slate-700 dark:text-slate-300 text-base leading-relaxed border-t border-slate-200/80 dark:border-white/10 pt-4">
          {{ item.answer }}
        </div>
      </Transition>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';

export interface FaqItem {
  question: string;
  answer: string;
}

defineProps<{
  items: FaqItem[];
}>();

const openIndex = ref<number | null>(0);

const toggle = (index: number) => {
  openIndex.value = openIndex.value === index ? null : index;
};
</script>

<style scoped>
.accordion-enter-active,
.accordion-leave-active {
  transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);
  max-height: 300px;
}

.accordion-enter-from,
.accordion-leave-to {
  opacity: 0;
  max-height: 0;
  padding-top: 0;
  padding-bottom: 0;
}
</style>

// components/common/FaqAccordion.tsx
'use client';

import React, { useState } from 'react';
import { ChevronDown } from 'lucide-react';
import { ApiFaq } from '@/services/api';

interface FaqAccordionProps {
  faqs: ApiFaq[];
}

export const FaqAccordion: React.FC<FaqAccordionProps> = ({ faqs }) => {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  const toggle = (idx: number) => {
    setOpenIndex(openIndex === idx ? null : idx);
  };

  return (
    <div className="flex flex-col gap-4 max-w-3xl mx-auto">
      {faqs.map((faq, idx) => {
        const isOpen = openIndex === idx;
        return (
          <div
            key={faq.id || idx}
            className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white/80 dark:bg-slate-900/80 backdrop-blur-md overflow-hidden transition-all duration-300"
          >
            <button
              onClick={() => toggle(idx)}
              className="w-full flex items-center justify-between p-6 text-left focus:outline-none"
            >
              <span className="font-bold text-slate-900 dark:text-white text-base md:text-lg pr-4">
                {faq.question}
              </span>
              <div className={`p-2 rounded-full bg-slate-100 dark:bg-slate-800 transition-transform duration-300 ${isOpen ? 'rotate-180 bg-amber-500/20 text-amber-500' : 'text-slate-500'}`}>
                <ChevronDown className="w-5 h-5" />
              </div>
            </button>
            {isOpen && (
              <div className="px-6 pb-6 pt-2 text-slate-600 dark:text-slate-300 text-sm md:text-base leading-relaxed border-t border-slate-100 dark:border-slate-800/60 animate-fade-in-up">
                {faq.answer}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
};
