// app/about/page.tsx
import type { Metadata } from 'next';
import { fetchTeamMembers } from '@/services/api';
import { BaseBadge } from '@/components/common/BaseBadge';
import { CompanyTimeline } from '@/components/sections/CompanyTimeline';
import { CtaBanner } from '@/components/sections/CtaBanner';
import { siteConfig } from '@/src/config/site.config';
import { Target, Eye, ShieldCheck } from 'lucide-react';
import { PlatformIcon } from '@/components/common/PlatformIcon';

export const metadata: Metadata = {
  title: 'About Us | Leadership & Engineering Story',
  description: 'Learn about SHP Technology, our leadership team, company timeline, and core engineering principles.'
};

export const revalidate = 60;

export default async function AboutPage() {
  const teamMembers = await fetchTeamMembers();

  return (
    <div className="py-16 md:py-24 bg-surface-main text-primaryText relative overflow-hidden">
      <div className="absolute inset-0 pointer-events-none" aria-hidden="true">
        <div className="absolute -top-32 left-1/2 -translate-x-1/2 w-[600px] h-[300px] rounded-full bg-brand-accent/10 blur-[120px]" />
      </div>

      <div className="container max-w-6xl mx-auto relative z-10">
        <div className="text-center max-w-3xl mx-auto mb-20">
          <BaseBadge variant="amber" className="mb-4 uppercase tracking-widest text-[10px]">
            About SHP Technology
          </BaseBadge>
          <h1 className="text-4xl md:text-6xl font-extrabold text-primaryText tracking-tight mb-6 leading-tight">
            Building High-Performance Software for the <span className="bg-gradient-to-r from-brand-accent to-brand-primary bg-clip-text text-transparent">Next Generation</span>
          </h1>
          <p className="text-secondaryText text-lg md:text-xl leading-relaxed">
            {siteConfig.description}
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-8 mb-24">
          <div className="p-8 rounded-3xl bg-surface-card border border-surface-border hover:border-brand-accent/40 shadow-xl transition-all duration-300">
            <div className="p-3.5 rounded-2xl bg-surface-subtle border border-surface-border w-fit mb-6 text-brand-accent">
              <Target className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-primaryText mb-3">Our Mission</h3>
            <p className="text-secondaryText text-sm leading-relaxed">
              Empower enterprise businesses worldwide with high-velocity, clean, and secure software solutions that automate operations and accelerate growth.
            </p>
          </div>

          <div className="p-8 rounded-3xl bg-surface-card border border-surface-border hover:border-brand-primary/40 shadow-xl transition-all duration-300">
            <div className="p-3.5 rounded-2xl bg-surface-subtle border border-surface-border w-fit mb-6 text-brand-primary">
              <Eye className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-primaryText mb-3">Our Vision</h3>
            <p className="text-secondaryText text-sm leading-relaxed">
              Become a globally recognized engineering powerhouse known for transparent client partnerships, top-tier technical craft, and reliable delivery.
            </p>
          </div>

          <div className="p-8 rounded-3xl bg-surface-card border border-surface-border hover:border-brand-accent/40 shadow-xl transition-all duration-300">
            <div className="p-3.5 rounded-2xl bg-surface-subtle border border-surface-border w-fit mb-6 text-brand-accent">
              <ShieldCheck className="w-6 h-6" />
            </div>
            <h3 className="text-xl font-bold text-primaryText mb-3">Our Commitment</h3>
            <p className="text-secondaryText text-sm leading-relaxed">
              Competitive, transparent pricing with no hidden fees, bi-weekly working demos, and responsive post-launch support backed by clear SLAs.
            </p>
          </div>
        </div>

        <div className="mb-24">
          <div className="text-center max-w-3xl mx-auto mb-16">
            <BaseBadge variant="amber" className="mb-4 uppercase tracking-widest text-[10px]">
              Leadership & Engineering
            </BaseBadge>
            <h2 className="text-3xl md:text-5xl font-extrabold text-primaryText tracking-tight mb-4">
              Meet the People Behind SHP
            </h2>
            <p className="text-secondaryText text-base md:text-lg">
              Experienced software architects, full-stack developers, and project leaders committed to your success.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {teamMembers.map((member) => (
              <div
                key={member.id || member.name}
                className="p-8 rounded-3xl bg-surface-card border border-surface-border hover:border-brand-accent/50 shadow-xl flex flex-col justify-between group transition-all duration-300 hover:-translate-y-1"
              >
                <div>
                  <div className="w-16 h-16 rounded-2xl bg-gradient-to-br from-brand-accent to-brand-accentHover flex items-center justify-center text-brand-buttonText font-extrabold text-xl mb-6 shadow-lg shadow-brand-accent/20 group-hover:scale-105 transition-transform">
                    {member.initials || member.name.split(' ').map((n) => n[0]).join('')}
                  </div>
                  <h3 className="text-xl font-bold text-primaryText mb-1">
                    {member.name}
                  </h3>
                  <span className="text-xs font-bold text-brand-accent uppercase tracking-wider block mb-4">
                    {member.role}
                  </span>
                  <p className="text-secondaryText text-sm leading-relaxed">
                    {member.bio}
                  </p>
                </div>

                <div className="flex items-center gap-3 pt-6 mt-6 border-t border-surface-border">
                  {member.linkedin_url && (
                    <a
                      href={member.linkedin_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="p-2 rounded-xl bg-surface-subtle text-secondaryText hover:text-[#0A66C2] transition-colors"
                      aria-label="LinkedIn Profile"
                    >
                      <PlatformIcon platform="linkedin" className="w-4 h-4" />
                    </a>
                  )}
                  {member.github_url && (
                    <a
                      href={member.github_url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="p-2 rounded-xl bg-surface-subtle text-secondaryText hover:text-primaryText transition-colors"
                      aria-label="GitHub Profile"
                    >
                      <PlatformIcon platform="github" className="w-4 h-4" />
                    </a>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>

        <CompanyTimeline />
        <CtaBanner />
      </div>
    </div>
  );
}

// src/views/About.vue
<template>
  <div class="page-about">
    <SectionContainer>
      <div class="max-w-4xl mx-auto text-center mb-12 animate-fade-in-up">
        <span class="inline-flex items-center gap-2 bg-brand-light dark:bg-slate-800 border border-brand-border dark:border-slate-700 px-3.5 py-1.5 rounded-full text-xs font-semibold text-primaryText mb-4">
          About SHP Technology
        </span>
        <h1 class="text-4xl md:text-5xl font-extrabold text-primaryText tracking-tight mb-4 leading-tight">
          We Build Solid Software for Businesses
        </h1>
        <p class="text-lg text-secondaryText leading-relaxed">
          We are a friendly team of developers and software builders who love making tools that work well and help your business grow.
        </p>
      </div>

      <div class="about-grid">
        <div class="about-text">
          <h3>Our Goal</h3>
          <p>
            Many business software programs are slow, complicated, or break easily. Our goal is to build simple, fast, and reliable software that works perfectly every time.
          </p>
          <h3>Our Way of Working</h3>
          <p>
            We focus on what works, not on fancy trends. Everything we build is tested carefully, runs fast without stopping, and comes with easy instructions.
          </p>
        </div>
        <div class="about-card">
          <div class="card-inner">
            <span class="card-tag">Company Performance Metrics</span>
            <div class="metrics-stack">
              <div v-for="m in companyData.metrics" :key="m.label" class="metric-row">
                <span class="m-val">{{ m.value }} {{ m.label }}</span>
                <span class="m-lbl">→ {{ m.tagline }} — {{ m.description }}</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </SectionContainer>

    <!-- Company Timeline Section -->
    <CompanyTimeline />

    <MethodologySection />

    <!-- Team & Leadership Section -->
    <SectionContainer
      tag="Our Team"
      title="Led by Experienced Engineering, Sales & Operations Leaders"
      subtitle="Our team brings deep domain experience across software development, full-stack engineering, client relations, and operational excellence."
    >
      <div class="team-grid">
        <BaseCard v-for="member in teamMembers" :key="member.id || member.name" class="team-card">
          <div class="avatar-circle" aria-hidden="true">{{ member.initials || member.name.split(' ').map(n => n[0]).join('').substring(0, 2) }}</div>
          <h3 class="member-name">{{ member.name }}</h3>
          <p class="member-role">{{ member.role }}</p>
          <p class="member-bio">{{ member.bio }}</p>
        </BaseCard>
      </div>
    </SectionContainer>

    <CtaBanner />
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue';
import SectionContainer from '@/components/layout/SectionContainer.vue';
import MethodologySection from '@/components/sections/MethodologySection.vue';
import CompanyTimeline from '@/components/sections/CompanyTimeline.vue';
import CtaBanner from '@/components/sections/CtaBanner.vue';
import BaseCard from '@/components/common/BaseCard.vue';
import { companyData } from '@/data/company';
import { useSeoMeta } from '@/composables/useSeoMeta';
import { fetchTeamMembers, type ApiTeamMember } from '@/services/api';

const teamMembers = ref<ApiTeamMember[]>(companyData.team.map((m, i) => ({
  id: i + 1,
  name: m.name,
  initials: m.initials,
  role: m.role,
  bio: m.bio,
  order: i + 1
})));

onMounted(async () => {
  teamMembers.value = await fetchTeamMembers(teamMembers.value);
});

useSeoMeta({
  title: 'About Our Company & Leadership',
  description: 'Learn about SHP Technology, our team of developers, our mission, and our software engineering philosophy.'
});
</script>

<style scoped>
.about-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: var(--space-8);
  align-items: center;
}

@media (min-width: 1024px) {
  .about-grid {
    grid-template-columns: 1.2fr 0.8fr;
  }
}

.about-text {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.about-text h3 {
  font-size: var(--fs-2xl);
  color: var(--text-primary);
}

.about-card {
  background-color: var(--bg-surface-subtle);
  color: var(--text-primary);
  border-radius: var(--radius-xl);
  padding: var(--space-8);
  border: 1px solid var(--border-color);
}

.card-tag {
  color: var(--brand-yellow-hover);
  font-size: var(--fs-xs);
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  display: block;
  margin-bottom: var(--space-6);
}

.metrics-stack {
  display: flex;
  flex-direction: column;
  gap: var(--space-4);
}

.metric-row {
  display: flex;
  flex-direction: column;
  border-bottom: 1px solid var(--border-color);
  padding-bottom: var(--space-3);
}

.m-val {
  font-size: var(--fs-2xl);
  font-weight: 800;
  color: var(--text-primary);
}

.m-lbl {
  font-size: var(--fs-xs);
  color: var(--text-secondary);
}

.team-grid {
  display: grid;
  grid-template-columns: 1fr;
  gap: var(--space-6);
}

@media (min-width: 768px) {
  .team-grid {
    grid-template-columns: repeat(3, 1fr);
  }
}

.team-card {
  text-align: center;
  display: flex;
  flex-direction: column;
  align-items: center;
}

.avatar-circle {
  width: 64px;
  height: 64px;
  border-radius: 50%;
  background-color: var(--brand-yellow-light);
  border: 2px solid var(--brand-yellow);
  color: var(--text-primary);
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 800;
  font-size: var(--fs-lg);
  margin-bottom: var(--space-4);
}

.member-name {
  font-size: var(--fs-lg);
  margin-bottom: 2px;
}

.member-role {
  font-size: var(--fs-xs);
  font-weight: 700;
  color: var(--brand-yellow-hover);
  margin-bottom: var(--space-3);
}

.member-bio {
  font-size: var(--fs-xs);
  color: var(--text-secondary);
}
</style>
