// components/common/BaseBadge.tsx
import React from 'react';

interface BaseBadgeProps {
  variant?: 'amber' | 'blue' | 'emerald' | 'slate';
  children: React.ReactNode;
  className?: string;
}

export const BaseBadge: React.FC<BaseBadgeProps> = ({
  variant = 'amber',
  children,
  className = ''
}) => {
  const variantStyles = {
    amber: 'bg-amber-500/10 dark:bg-amber-500/15 border-amber-500/30 text-amber-600 dark:text-amber-400',
    blue: 'bg-blue-500/10 dark:bg-blue-500/15 border-blue-500/30 text-blue-600 dark:text-blue-400',
    emerald: 'bg-emerald-500/10 dark:bg-emerald-500/15 border-emerald-500/30 text-emerald-600 dark:text-emerald-400',
    slate: 'bg-slate-500/10 dark:bg-slate-500/15 border-slate-500/30 text-slate-700 dark:text-slate-300',
  };

  return (
    <span
      className={`inline-flex items-center px-3 py-1 rounded-full text-xs font-semibold border backdrop-blur-sm ${variantStyles[variant]} ${className}`}
    >
      {children}
    </span>
  );
};

// src/components/common/BaseBadge.vue
<template>
  <span :class="['inline-flex items-center px-3 py-1 rounded-full text-xs font-bold leading-none backdrop-blur-md shadow-xs transition-colors', badgeClasses]">
    <slot />
  </span>
</template>

<script setup lang="ts">
import { computed } from 'vue';

const props = withDefaults(
  defineProps<{
    variant?: 'yellow' | 'sky' | 'neutral' | 'dark' | 'success';
  }>(),
  {
    variant: 'yellow'
  }
);

const badgeClasses = computed(() => {
  switch (props.variant) {
    case 'yellow':
      return 'bg-amber-500/15 text-amber-800 dark:text-amber-300 border border-amber-500/30';
    case 'sky':
      return 'bg-sky-500/15 text-sky-800 dark:text-sky-300 border border-sky-500/30';
    case 'neutral':
      return 'bg-slate-200/80 dark:bg-slate-800/80 text-slate-800 dark:text-slate-200 border border-slate-300 dark:border-white/10';
    case 'dark':
      return 'bg-slate-900 text-white dark:bg-slate-800/90 dark:text-slate-100 border border-slate-700 dark:border-white/10';
    case 'success':
      return 'bg-emerald-500/15 text-emerald-800 dark:text-emerald-300 border border-emerald-500/30';
    default:
      return 'bg-amber-500/15 text-amber-800 dark:text-amber-300 border border-amber-500/30';
  }
});
</script>
